[package]
name = "rsp-client-executor"
description = ""
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
bincode.workspace = true
cfg-if.workspace = true
itertools.workspace = true
kzg-rs.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_with.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true

# workspace
rsp-primitives.workspace = true
rsp-mpt.workspace = true

# reth
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-errors.workspace = true
reth-ethereum-consensus.workspace = true
reth-ethereum-primitives.workspace = true
reth-evm-ethereum.workspace = true
reth-evm.workspace = true
reth-execution-types.workspace = true
reth-primitives-traits.workspace = true
reth-primitives.workspace = true
reth-trie.workspace = true

# revm
revm-primitives.workspace = true
revm.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# pico
pico-sdk.workspace = true
pico-patch-libs.workspace = true

[dev-dependencies]
